name: flutter_goal_cast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shared_preferences: ^2.1.1
  animate_do: ^4.2.0
  another_flutter_splash_screen: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/tabbar/
    - assets/images/bg/
    - assets/images/map/

  fonts:
    - family: Manrope
      fonts: 
        - asset: assets/fonts/Manrope/Manrope-VariableFont_wght.ttf
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          style: italic